export const colores = [
  {
    codigo: '765',
    name: 'Blanco Ostión',
    color: '#fcf8ef',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '701',
    name: 'Champaña',
    color: '#f5e6cf',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '704',
    name: 'Crema',
    color: '#f8e2bb',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '745',
    name: 'Salmón',
    color: '#eec4ac',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '747',
    name: 'Cantera Mexicana',
    color: '#e6c49f',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '715',
    name: 'Mostaza',
    color: '#ac8b3a',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '764',
    name: 'Capuchino',
    color: '#94856e',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '725',
    name: 'Chocolate',
    color: '#4f3127',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '724',
    name: 'Rojo Óxido',
    color: '#622103',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '722',
    name: 'Rojo',
    color: '#b40c01',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '712',
    name: 'Mandarina',
    color: '#e16951',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '746',
    name: 'Naranja Colonial',
    color: '#e38f39',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '729',
    name: 'Amarillo Napolitano',
    color: '#edb582',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '735',
    name: 'Durazno',
    color: '#f1c981',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '739',
    name: 'Amarillo Colonial',
    color: '#f1c967',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '743',
    name: 'Amarillo Solar',
    color: '#f9ea99',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '720',
    name: 'Amarillo Limón',
    color: '#f5df34',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '703',
    name: 'Verde Manzana',
    color: '#96D346',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '749',
    name: 'Aqua',
    color: '#8dc0bb',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '740',
    name: 'Verde Imperial',
    color: '#98a989',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '721',
    name: 'Verde Esmeralda',
    color: '#2a3829',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '718',
    name: 'Azul Colonial',
    color: '#3932a4',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '748',
    name: 'Azul Océano',
    color: '#3157a0',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '714',
    name: 'Azul Vallarta',
    color: '#73b5e5',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '733',
    name: 'Rosa Mexicano',
    color: '#bd486b',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '741',
    name: 'Frambuesa',
    color: '#831850',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '744',
    name: 'Uva',
    color: '#402353',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '719',
    name: 'Azul Rey',
    color: '#1d0050',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '742',
    name: 'Gris Oxford',
    color: '#929292',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '723',
    name: 'Negro',
    color: '#000000',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '700',
    name: 'Blanco',
    color: '#ffffff',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '770',
    name: 'Blanco Mate',
    color: '#ffffff',
    product: 'vintek',
    cat: 'vinilicas',
  },
  {
    codigo: '402',
    name: 'Blanco Ostión',
    color: '#e2dcd0',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '430',
    name: 'Arena Real',
    color: '#f6e0c9',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '427',
    name: 'Champaña',
    color: '#e9d8c6',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '415',
    name: 'Piñon',
    color: '#dcbc93',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '438',
    name: 'Adobe Real',
    color: '#b1935f',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '417',
    name: 'Sándalo',
    color: '#836a4c',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '439',
    name: 'Terracota',
    color: '#793f33',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '410',
    name: 'Ladrillo Hacienda',
    color: '#ba6b4a',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '414',
    name: 'Rojo',
    color: '#c0292a',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '428',
    name: 'Naranja',
    color: '#e58847',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '426',
    name: 'Amarillo',
    color: '#f5da33',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '404',
    name: 'Paja',
    color: '#f7e38d',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '431',
    name: 'Verde Apio',
    color: '#e6f9c9',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '420',
    name: 'Verde Manzana',
    color: '#bed668',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '436',
    name: 'Verde Olivo',
    color: '#9b966c',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '429',
    name: 'Zarzamora',
    color: '#643363',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '434',
    name: 'Azul Profundo',
    color: '#1b3069',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '435',
    name: 'Azul Infinito',
    color: '#617dc7',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '437',
    name: 'Azul Cielo',
    color: '#d5e7f1',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '432',
    name: 'Acero',
    color: '#6d8283',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '433',
    name: 'Gris Bahía',
    color: '#dcddd8',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '400',
    name: 'Blanco',
    color: '#ffffff',
    product: 'realtek',
    cat: 'vinilicas',
  },
  {
    codigo: '425',
    name: 'Negro',
    color: '#000000',
    product: 'realtek',
    cat: 'vinilicas',
  },

  {
    codigo: '500',
    name: 'Blanco',
    color: '#ffffff',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '501',
    name: 'Arena',
    color: '#f4e8c3',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '502',
    name: 'Turquesa',
    color: '#99dbbc',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '503',
    name: 'Blanco Ostión',
    color: '#f1f1e2',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '504',
    name: 'Marfil',
    color: '#ffe7bc',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '505',
    name: 'Verde Manzana',
    color: '#b0d770',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '506',
    name: 'Azul',
    color: '#42cce4',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '507',
    name: 'Naranja',
    color: '#ff501e',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '508',
    name: 'Rojo',
    color: '#ff361a',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '509',
    name: 'Gris Bahia',
    color: '#8da9a3',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },
  {
    codigo: '510',
    name: 'Piñon',
    color: '#eccba6',
    product: 'vinipesa_satin',
    cat: 'vinilicas',
  },

  {
    codigo: '314',
    name: 'Amarillo Limón',
    color: '#f5da33',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '311',
    name: 'Marfil',
    color: '#f8e6c2',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '319',
    name: 'Durazno',
    color: '#eec0a9',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '305',
    name: 'Coral',
    color: '#e79393',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '324',
    name: 'Rosado',
    color: '#ecb1c5',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '313',
    name: 'Tangerina',
    color: '#e68f5c',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '308',
    name: 'Naranja',
    color: '#d85032',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '323',
    name: 'Rojo Bandera',
    color: '#b82f2f',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '317',
    name: 'Rojo Teja',
    color: '#733119',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '303',
    name: 'Violeta Intenso',
    color: '#64439e',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '309',
    name: 'Azul Rey',
    color: '#1a2857',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '318',
    name: 'Azul Medio',
    color: '#3d6eb3',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '302',
    name: 'Azul Horizonte',
    color: '#98caed',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '310',
    name: 'Verde Manzana',
    color: '#c8da62',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '322',
    name: 'Verde Esmeralda',
    color: '#32523a',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '325',
    name: 'Verde Milicia',
    color: '#48492a',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '300',
    name: 'Blanco',
    color: '#ffffff',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },
  {
    codigo: '321',
    name: 'Negro',
    color: '#040609',
    product: 'vinipesa_mate',
    cat: 'vinilicas',
  },

  {
    codigo: '1300',
    name: 'Blanco',
    color: '#ffffff',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1313',
    name: 'Blanco Ostión',
    color: '#f9f3e7',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1304',
    name: 'Marfil',
    color: '#f8e6c2',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1303',
    name: 'Arena',
    color: '#f2cf95',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1305',
    name: 'Chabacano',
    color: '#efbb70',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1311',
    name: 'Salmón',
    color: '#edb585',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1306',
    name: 'Naranja',
    color: '#e17549',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1301',
    name: 'Flamingo',
    color: '#cf6080',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1312',
    name: 'Azul Eterno',
    color: '#8686b8',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1309',
    name: 'Azul',
    color: '#73b5e5',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1308',
    name: 'Turquesa',
    color: '#7cd1a8',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1310',
    name: 'Verde Manzana',
    color: '#c0d548',
    product: 'vini_plus',
    cat: 'vinilicas',
  },
  {
    codigo: '1400',
    name: 'Blanco',
    color: '#ffff',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1406',
    name: 'Violeta',
    color: '#ccc0e8',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1418',
    name: 'Rosa Ligero',
    color: '#f1dcdb',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1414',
    name: 'Roble',
    color: '#634833',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1408',
    name: 'Amarillo',
    color: '#f4db7f',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1402',
    name: 'Azul Olimpia',
    color: '#8ab5e7',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1409',
    name: 'Blanco Ostión',
    color: '#e2dcd0',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1413',
    name: 'Rojo Óxido',
    color: '#8c4941',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1415',
    name: 'Verde Manzana',
    color: '#b5c668',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1405',
    name: 'Azul Cascada',
    color: '#b1d5e1',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1401',
    name: 'Marfil',
    color: '#f6dfc0',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1417',
    name: 'Escarlata',
    color: '#9f3b35',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1411',
    name: 'Pistache',
    color: '#b9cead',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1407',
    name: 'Turquesa Claro',
    color: '#ade6d5',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1410',
    name: 'Durazno',
    color: '#f1cb9e',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1416',
    name: 'Mandarina',
    color: '#e48454',
    product: 'colorbel',
    cat: 'vinilicas',
  },
  {
    codigo: '1403',
    name: 'Mamey',
    color: '#eaaa87',
    product: 'colorbel',
    cat: 'vinilicas',
  },

  {
    codigo: '1241',
    name: 'Oro',
    color: '#b09345',
    product: 'clasico',
    cat: 'esmaltes',
  },
  {
    codigo: '1240',
    name: 'Aluminio',
    color: '#a4a4a4',
    product: 'clasico',
    cat: 'esmaltes',
  },
  {
    codigo: '1242',
    name: 'Cobre',
    color: '#9a6440',
    product: 'clasico',
    cat: 'esmaltes',
  },

  {
    codigo: '1200',
    name: 'Blanco',
    color: '#ffff',
    product: 'clasico',
    cat: 'esmaltes',
  },
  {
    codigo: '1221',
    name: 'Negro',
    color: '#000000',
    product: 'clasico',
    cat: 'esmaltes',
  },
  {
    codigo: '239',
    name: 'Verde Manzana',
    color: '#84b645',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '236',
    name: 'Azul Holandés',
    color: '#3965bb',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '223',
    name: 'Negro',
    color: '#000000',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '200',
    name: 'Blanco',
    color: '#ffffff',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '235',
    name: 'Aluminio',
    color: '#b4b6b5',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '240',
    name: 'Transparente',
    color: 'bg-transparent',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '238',
    name: 'Negro Mate',
    color: '#1f1f1f',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '237',
    name: 'Blanco Mate',
    color: '#ffffff',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '241',
    name: 'Azul Orgánico',
    color: '#1f3686',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '242',
    name: 'Verde Orgánico',
    color: '#335835',
    product: 'tropimarsur',
    cat: 'esmaltes',
  },
  {
    codigo: '1004',
    name: 'Granada',
    color: '#ce3204',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1008',
    name: 'Rojo Cereza',
    color: '#9b011d',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1012',
    name: 'Rojo Indio',
    color: '#742811',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1024',
    name: 'Marrón',
    color: '#810f31',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1016',
    name: 'Chocolate',
    color: '#342609',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1009',
    name: 'Castaño',
    color: '#9e7150',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1003',
    name: 'Amarillo Óxido',
    color: '#aa762a',
    product: 'tropimar',
    cat: 'esmaltes',
  },

  {
    codigo: '1007',
    name: 'Verde Real',
    color: '#4e8357',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1028',
    name: 'Blanco Hueso',
    color: '#eee7d3',
    product: 'tropimar',
    cat: 'esmaltes',
  },

  {
    codigo: '1000',
    name: 'Blanco',
    color: '#ffffff',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1014',
    name: 'Negro',
    color: '#000000',
    product: 'tropimar',
    cat: 'esmaltes',
  },
  {
    codigo: '1000',
    name: 'Blanco',
    color: '#ffffff',
    product: 'tropimar_aqua',
    cat: 'esmaltes',
  },
  {
    codigo: '4001',
    name: 'Amarillo',
    color: '#f7ad02',
    product: 'tropimar_aqua',
    cat: 'esmaltes',
  },
  {
    codigo: '4002',
    name: 'Azul',
    color: '#17378a',
    product: 'tropimar_aqua',
    cat: 'esmaltes',
  },
  {
    codigo: '3003',
    name: 'Rojo',
    color: '#e20620',
    product: 'tropimar_aqua',
    cat: 'esmaltes',
  },
  {
    codigo: '1715',
    name: 'Amarillo Limón',
    color: '#ffd300',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1716',
    name: 'Azul Orgánico',
    color: '#1f317b',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1711',
    name: 'Verde Orgánico',
    color: '#007740',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1713',
    name: 'Amarillo Cromo',
    color: '#f8ad00',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1717',
    name: 'Azul Holandés',
    color: '#006cb4',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1712',
    name: 'Verde Pradera',
    color: '#008645',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1714',
    name: 'Amarillo Óxido',
    color: '#ca8107',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1707',
    name: 'Café',
    color: '#583725',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1708',
    name: 'Chocolate ',
    color: '#3a2105',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1718',
    name: 'Marrón',
    color: '#81152d',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1706',
    name: 'Rojo Óxido',
    color: '#8e3713',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1709',
    name: 'Chocolate Mate',
    color: '#3a2105',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1710',
    name: 'Rojo',
    color: '#e3051f',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1719',
    name: 'Naranja',
    color: '#e74915',
    product: 'brigadier',
    cat: 'esmaltes',
  },
  {
    codigo: '1704',
    name: 'Transparente',
    color: 'transparent',
    product: 'brigadier',
    cat: 'esmaltes',
  },

  {
    codigo: '1100',
    name: 'Blanco',
    color: '#ffffff',
    product: 'canada',
    cat: 'esmaltes',
  },
  {
    codigo: '1101',
    name: 'Negro',
    color: '#000000',
    product: 'canada',
    cat: 'esmaltes',
  },
  {
    codigo: '2140',
    name: 'Azul Cielo',
    color: '#a8dbec',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2144',
    name: 'Amarillo Caterpilar',
    color: '#c8903b',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2145',
    name: 'Crema',
    color: '#eed89c',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2146',
    name: 'Chocolate',
    color: '#342a29',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2147',
    name: 'Verde Óleo',
    color: '#8aa96e',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2148',
    name: 'Rosa Taxi',
    color: '#ab005e',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2170',
    name: 'Blanco',
    color: '#ffffff',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2171',
    name: 'Negro',
    color: '#000000',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2176',
    name: 'Rosa Mexicano',
    color: '#cf6080',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2177',
    name: 'Morado',
    color: '#473f68',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2178',
    name: 'Azul Ford',
    color: '#03023b',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2182',
    name: 'Amarillo Limón',
    color: '#f1c52e',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2183',
    name: 'Azul Holandés',
    color: '#467cb8',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2184',
    name: 'Verde Hoja',
    color: '#3e6632',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2194',
    name: 'Transparente',
    color: 'bg-transparent',
    product: 'brillantes',
    cat: 'aerosoles',
  },
  {
    codigo: '2139',
    name: 'Negro Alta Temperatura',
    color: '#000000',
    product: 'alta_temperatura',
    cat: 'aerosoles',
  },
  {
    codigo: '2162',
    name: 'Aluminio Alta Temperatura',
    color: '#b7b7b9',
    product: 'alta_temperatura',
    cat: 'aerosoles',
  },
  {
    codigo: '2188',
    name: 'Oro Intenso',
    color: '#966e3b',
    product: 'niquelados',
    cat: 'aerosoles',
  },
  {
    codigo: '2192',
    name: 'Aluminio',
    color: '#a4a4a4',
    product: 'niquelados',
    cat: 'aerosoles',
  },
  {
    codigo: '2193',
    name: 'Oro Brillante',
    color: '#ae9350',
    product: 'niquelados',
    cat: 'aerosoles',
  },
  {
    codigo: '2198',
    name: 'Cromo',
    color: '#b4b4b4',
    product: 'niquelados',
    cat: 'aerosoles',
  },
  {
    codigo: '2199',
    name: 'Cobre',
    color: '#9a6440',
    product: 'niquelados',
    cat: 'aerosoles',
  },
  {
    codigo: '2153',
    name: 'Verde Fluorescente',
    color: '#88eb39',
    product: 'fluorescentes',
    cat: 'aerosoles',
  },
  {
    codigo: '2154',
    name: 'Rosa Fluorescente',
    color: '#db1b8d',
    product: 'fluorescentes',
    cat: 'aerosoles',
  },
  {
    codigo: '2158',
    name: 'Amarillo Fluorescente',
    color: '#eeff3c',
    product: 'fluorescentes',
    cat: 'aerosoles',
  },
  {
    codigo: '2159',
    name: 'Naranja Fluorescente',
    color: '#dc4409',
    product: 'fluorescentes',
    cat: 'aerosoles',
  },
  {
    codigo: '2185',
    name: 'Naranja',
    color: '#d6372a',
    product: 'seguridad',
    cat: 'aerosoles',
  },
  {
    codigo: '2186',
    name: 'Amarillo Medio',
    color: '#e69033',
    product: 'seguridad',
    cat: 'aerosoles',
  },
  {
    codigo: '2189',
    name: 'Gris Acero',
    color: '#7f8487',
    product: 'seguridad',
    cat: 'aerosoles',
  },
  {
    codigo: '2190',
    name: 'Rojo',
    color: '#ae1213',
    product: 'seguridad',
    cat: 'aerosoles',
  },
  {
    codigo: '2142',
    name: 'Lila Metálico',
    color: '#634d7c',
    product: 'metalicos',
    cat: 'aerosoles',
  },
  {
    codigo: '2143',
    name: 'Negro Metálico',
    color: '#000000',
    product: 'metalicos',
    cat: 'aerosoles',
  },
  {
    codigo: '2174',
    name: 'Azul Metálico',
    color: '#39619f',
    product: 'metalicos',
    cat: 'aerosoles',
  },
  {
    codigo: '2175',
    name: 'Verde Metálico',
    color: '#3b674c',
    product: 'metalicos',
    cat: 'aerosoles',
  },
  {
    codigo: '2180',
    name: 'Rojo Metálico',
    color: '#7b002e',
    product: 'metalicos',
    cat: 'aerosoles',
  },
  {
    codigo: '2195',
    name: 'Primario Gris',
    color: '#83888e',
    product: 'anticorrosivos',
    cat: 'aeroloses',
  },
  {
    codigo: '2196',
    name: 'Primario Rojo Óxido',
    color: '#85362f',
    product: 'anticorrosivos',
    cat: 'aeroloses',
  },

  {
    codigo: '2172',
    name: 'Blanco Mate',
    color: '#ffffff',
    product: 'mate',
    cat: 'aerosoles',
  },
  {
    codigo: '2173',
    name: 'Negro Mate',
    color: '#1f1f1f',
    product: 'mate',
    cat: 'aerosoles',
  },
  {
    codigo: '2141',
    name: 'Transparente Mate',
    color: 'bg-transparent',
    product: 'mate',
    cat: 'aerosoles',
  },

  {
    codigo: '2191',
    name: 'Negro Satinado',
    color: '#040609',
    product: 'satin_aerosol',
    cat: 'aerosoles',
  },
  {
    codigo: '1521',
    name: 'Negro',
    color: '#111315',
    product: 'elite',
    cat: 'ferre',
  },

  {
    codigo: '1500',
    name: 'Blanco',
    color: '#ffffff',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1501',
    name: 'Blanco Ostión',
    color: '#f2f3e2',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1512',
    name: 'Arena',
    color: '#ebe4c2',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1511',
    name: 'Marfil',
    color: '#f8dbb3',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1515',
    name: 'Piñón',
    color: '#c7af96',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1507',
    name: 'Amarillo Soleado',
    color: '#f5c67d',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1514',
    name: 'Amarillo Limón',
    color: '#f6d46a',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1520',
    name: 'Amarillo Napolitano',
    color: '#f4a360',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1516',
    name: 'Amarillo Ocre',
    color: '#ae7f50',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1513',
    name: 'Tangerina',
    color: '#f48a65',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1508',
    name: 'Naranja',
    color: '#e95f48',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1517',
    name: 'Rojo Teja',
    color: '#562620',
    product: 'elite',
    cat: 'ferre',
  },

  {
    codigo: '1523',
    name: 'Rojo Bandera',
    color: '#be4342',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1519',
    name: 'Durazno',
    color: '#f2b499',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1505',
    name: 'Coral',
    color: '#f38b87',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1524',
    name: 'Rosado',
    color: '#f4a3b2',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1503',
    name: 'Violeta Intenso',
    color: '#434b97',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1510',
    name: 'Verde Manzana',
    color: '#a2d681',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1525',
    name: 'Milicia',
    color: '#2a3524',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1522',
    name: 'Verde Esmeralda',
    color: '#1c4233',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1509',
    name: 'Azul Rey',
    color: '#11203c',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1518',
    name: 'Azul Medio',
    color: '#276fa8',
    product: 'elite',
    cat: 'ferre',
  },
  {
    codigo: '1502',
    name: 'Azul Horizonte',
    color: '#6cc5d9',
    product: 'elite',
    cat: 'ferre',
  },

  // Imperial

  {
    codigo: '800',
    name: 'Blanco',
    color: '#f5efe1',
    product: 'imperial',
    cat: 'ferre',
  },
  {
    codigo: '813',
    name: 'Blanco Ostión',
    color: '#f5f1e2',
    product: 'imperial',
    cat: 'ferre',
  },
  {
    codigo: '804',
    name: 'Marfil',
    color: '#f7e2c3',
    product: 'imperial',
    cat: 'ferre',
  },
  {
    codigo: '803',
    name: 'Arena',
    color: '#efcba3',
    product: 'imperial',
    cat: 'ferre',
  },

  {
    codigo: '805',
    name: 'Chabacano',
    color: '#ecba88',
    product: 'imperial',
    cat: 'ferre',
  },
  {
    codigo: '811',
    name: 'Salmón',
    color: '#edb694',
    product: 'imperial',
    cat: 'ferre',
  },

  {
    codigo: '806',
    name: 'Naranja',
    color: '#e38768',
    product: 'imperial',
    cat: 'ferre',
  },
  {
    codigo: '801',
    name: 'Flamingo',
    color: '#ce7888',
    product: 'imperial',
    cat: 'ferre',
  },

  {
    codigo: '812',
    name: 'Azul Eterno',
    color: '#7090b1',
    product: 'imperial',
    cat: 'ferre',
  },
  {
    codigo: '809',
    name: 'Azul',
    color: '#49bcd8',
    product: 'imperial',
    cat: 'ferre',
  },

  {
    codigo: '808',
    name: 'Turquesa',
    color: '#54c9b6',
    product: 'imperial',
    cat: 'ferre',
  },
  {
    codigo: '810',
    name: 'Verde Manzana',
    color: '#b1cc7b',
    product: 'imperial',
    cat: 'ferre',
  },

  {
    codigo: '5085',
    name: 'Amarillo Limón',
    color: '#ffd74b',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5083',
    name: 'Amarillo Cromo',
    color: '#fc9f3f',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5084',
    name: 'Amarillo Óxido',
    color: '#ba6f36',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5088',
    name: 'Marrón',
    color: '#7a1b34',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5077',
    name: 'Café',
    color: '#3d1d17',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5078',
    name: 'Chocolate Brillante',
    color: '#1d0e0d',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5081',
    name: 'Verde Orgánico',
    color: '#157541',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5082',
    name: 'Verde Pradera',
    color: '#268d49',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5076',
    name: 'Rojo Óxido',
    color: '#7f3126',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5080',
    name: 'Rojo',
    color: '#f13434',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },

  {
    codigo: '5089',
    name: 'Naranja',
    color: '#f6552e',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5079',
    name: 'Chocolate Mate',
    color: '#1d0e0d',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5087',
    name: 'Azul Holandés',
    color: '#0774ac',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5086',
    name: 'Azul Orgánico',
    color: '#0f3988',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5075',
    name: 'Aluminio',
    color: '#9caea2',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5090',
    name: 'Gris Acero',
    color: '#7b8d8b',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5072',
    name: 'Negro',
    color: '#111315',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5073',
    name: 'Negro Mate',
    color: '#1c1f20',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5074',
    name: 'Transparente',
    color: 'bg-transparent',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5071',
    name: 'Blanco Mate',
    color: '#ffffff',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5070',
    name: 'Blanco',
    color: '#ffffff',
    product: 'esmalte_ferre',
    cat: 'ferre',
  },
  {
    codigo: '5052',
    name: 'Amarillo Cromo',
    color: '#fd8d43',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5057',
    name: 'Amarillo Limón',
    color: '#ffd74b',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5056',
    name: 'Azul Holandés',
    color: '#0774ac',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5054',
    name: 'Verde Intenso',
    color: '#164b35',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5053',
    name: 'Rojo Cereza',
    color: '#a72930',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5055',
    name: 'Chocolate',
    color: '#191612',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5062',
    name: 'Chocolate Mate',
    color: '#1b1713',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5059',
    name: 'Gris Tornado',
    color: '#8c9a89',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5058',
    name: 'Blanco Ostión',
    color: '#d1d8c2',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5061',
    name: 'Negro',
    color: '#111315',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5060',
    name: 'Blanco',
    color: '#ffffff',
    product: 'esmalte_ferre2',
    cat: 'ferre',
  },
  {
    codigo: '5030',
    name: 'Gris',
    color: '#46534d',
    product: 'primario_herreros',
    cat: 'ferre',
  },
  {
    codigo: '5031',
    name: 'Rojo Óxido',
    color: '#733b31',
    product: 'primario_herreros',
    cat: 'ferre',
  },
  {
    codigo: '5008',
    name: 'Gris',
    color: '#47534d',
    product: 'primario_rtu',
    cat: 'ferre',
  },
  {
    codigo: '5009',
    name: 'Rojo Óxido',
    color: '#733b31',
    product: 'primario_rtu',
    cat: 'ferre',
  },
  {
    codigo: '3080-01',
    name: 'Blanco',
    color: '#ffffff',
    product: 'laca_ferre',
    cat: 'ferre',
  },
  {
    codigo: '3092',
    name: 'Chocolate Oscuro',
    color: '#07050a',
    product: 'laca_ferre',
    cat: 'ferre',
  },
  {
    codigo: '3093',
    name: 'Chocolate Medio',
    color: '#11080e',
    product: 'laca_ferre',
    cat: 'ferre',
  },

  {
    codigo: '3074',
    name: 'Blanco',
    color: '#ffffff',
    product: 'primer_ferre',
    cat: 'ferre',
  },
  {
    codigo: '3084',
    name: 'Amarillo Oro',
    color: '#f19e34',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3080',
    name: 'Blanco',
    color: '#fefefe',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3081',
    name: 'Negro',
    color: '#010101',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3090',
    name: 'Azul',
    color: '#030d31',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3089',
    name: 'Wengue',
    color: '#010101',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3096',
    name: 'Rojo Vivo',
    color: '#e41f28',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3082',
    name: 'Amarillo Óxido',
    color: '#d38f3a',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3087',
    name: 'Marrón',
    color: '#490115',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3083',
    name: 'Amarillo Limón',
    color: '#f9d835',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3085',
    name: 'Rojo Óxido',
    color: '#90391e',
    product: 'laca_century',
    cat: 'maderas',
  },
  {
    codigo: '3084',
    name: 'Chocolate',
    color: '#010101',
    product: 'laca_century',
    cat: 'maderas',
  },

  {
    codigo: '3072',
    name: 'Rojo Óxido',
    color: '#90391e',
    product: 'primer_nitrocelulosa',
    cat: 'maderas',
  },
  {
    codigo: '3073',
    name: 'Chocolate',
    color: '#2a180e',
    product: 'primer_nitrocelulosa',
    cat: 'maderas',
  },

  {
    codigo: '3073',
    name: 'Chocolate',
    color: '#2a180e',
    product: 'primer_nitrocelulosa',
    cat: 'maderas',
  },

  {
    codigo: '3209',
    name: 'Maple',
    color_imagen: '/muestrario/maple.jpg',
    product: 'barniz_entintado',
    cat: 'maderas',
  },
  {
    codigo: '3212',
    name: 'Nogal Clásico',
    color_imagen: '/muestrario/nogal_calsico.jpg',
    product: 'barniz_entintado',
    cat: 'maderas',
  },
  {
    codigo: '3210',
    name: 'Magnolia',
    color_imagen: '/muestrario/magnolia.jpg',
    product: 'barniz_entintado',
    cat: 'maderas',
  },
  {
    codigo: '3211',
    name: 'Caoba Clásico',
    color_imagen: '/muestrario/caoba_clsico.jpg',
    product: 'barniz_entintado',
    cat: 'maderas',
  },
  {
    codigo: '3206',
    name: 'Chocolate',
    color_imagen: '/muestrario/chocolate.jpg',
    product: 'barniz_entintado',
    cat: 'maderas',
  },

  {
    codigo: '3215',
    name: 'Nogal Americano',
    color_imagen: '/muestrario/nogal_americano.jpg',
    product: 'barniz_entintado_ferre',
    cat: 'ferre',
  },
  {
    codigo: '3216',
    name: 'Chocolate',
    color_imagen: '/muestrario/chocolate.jpg',
    product: 'barniz_entintado_ferre',
    cat: 'ferre',
  },
  {
    codigo: '3217',
    name: 'Caoba Clásico',
    color_imagen: '/muestrario/caoba_clsico.jpg',
    product: 'barniz_entintado_ferre',
    cat: 'ferre',
  },
  {
    codigo: '3218',
    name: 'Amaranto',
    color_imagen: '/muestrario/amaranto.jpg',
    product: 'barniz_entintado_ferre',
    cat: 'ferre',
  },

  {
    codigo: '3033',
    name: 'Chocolate',
    color_imagen: '/muestrario_tintas/chocolate.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },
  {
    codigo: '3039',
    name: 'Olmo',
    color_imagen: '/muestrario_tintas/olmo.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },
  {
    codigo: '3040',
    name: 'Early American',
    color_imagen: '/muestrario_tintas/early_american.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },
  {
    codigo: '3038',
    name: 'Caoba Comercial',
    color_imagen: '/muestrario_tintas/caoba_comercial.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },
  {
    codigo: '3031',
    name: 'Caoba Clásico',
    color_imagen: '/muestrario_tintas/caoba_clasico.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },
  {
    codigo: '3030',
    name: 'Nogal Americano',
    color_imagen: '/muestrario_tintas/nogal_americano.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },
  {
    codigo: '3032',
    name: 'Amaranto',
    color_imagen: '/muestrario_tintas/amaranto.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },

  {
    codigo: '3036',
    name: 'Cedro',
    color_imagen: '/muestrario_tintas/cedro.jpg',
    product: 'tintas_aceite',
    cat: 'maderas',
  },

  {
    codigo: '3013',
    name: 'Chocolate',
    color_imagen: '/muestrario_tintas/chocolate.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3019',
    name: 'Olmo',
    color_imagen: '/muestrario_tintas/olmo.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3020',
    name: 'Early American',
    color_imagen: '/muestrario_tintas/early_american.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3018',
    name: 'Caoba Comercial',
    color_imagen: '/muestrario_tintas/caoba_comercial.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3011',
    name: 'Caoba Clásico',
    color_imagen: '/muestrario_tintas/caoba_clasico.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3010',
    name: 'Nogal Americano',
    color_imagen: '/muestrario_tintas/nogal_americano.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3012',
    name: 'Amaranto',
    color_imagen: '/muestrario_tintas/amaranto.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3015',
    name: 'Nogal Obscuro',
    color_imagen: '/muestrario_tintas/nogal_obscuro.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3014',
    name: 'Magnolia',
    color_imagen: '/muestrario_tintas/magnolia.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3017',
    name: 'Roble',
    color_imagen: '/muestrario_tintas/roble.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '3016',
    name: 'Cedro',
    color_imagen: '/muestrario_tintas/cedro.jpg',
    product: 'tintas_alcohol',
    cat: 'maderas',
  },
  {
    codigo: '2149',
    name: 'Caoba',
    color: '#723206',
    product: 'aerosol_madera',
    cat: 'aerosoles',
  },
  {
    codigo: '2150',
    name: 'Nogal',
    color: '#512906',
    product: 'aerosol_madera',
    cat: 'aerosoles',
  },

  {
    codigo: '5000',
    name: 'Blanco',
    color: '#ffffff',
    product: 'vulcan_anticorrosivo',
    cat: 'vinilicas',
  },

  {
    codigo: '5001',
    name: 'Rojo Óxido',
    color: '#90391e',
    product: 'vulcan_anticorrosivo',
    cat: 'vinilicas',
  },
  {
    codigo: '5002',
    name: 'Gris',
    color: '#47534d',
    product: 'vulcan_anticorrosivo',
    cat: 'vinilicas',
  },
  {
    codigo: '5003',
    name: 'Negro',
    color: '#000000',
    product: 'vulcan_anticorrosivo',
    cat: 'vinilicas',
  },
  {
    codigo: '5004',
    name: 'Naranja',
    color: '#d6372a',
    product: 'vulcan_miniogenuino',
    cat: 'vinilicas',
  },
  {
    codigo: '5005',
    name: 'Naranja',
    color: '#d6372a',
    product: 'vulcan_minioeconomico',
    cat: 'vinilicas',
  },
  {
    codigo: '5006',
    name: 'Aamarillo',
    color: '#F59E0B',
    product: 'vulcan_comatozinc',
    cat: 'vinilicas',
  },
  {
    codigo: '5007',
    name: 'Gris',
    color: '#47534d',
    product: 'vulcan_secadorapido',
    cat: 'vinilicas',
  },
  {
    codigo: '5040',
    name: 'Blanco',
    color: '#ffffff',
    product: 'vulcan_secadoexpress',
    cat: 'vinilicas',
  },
  {
    codigo: '5041',
    name: 'Rojo Óxido',
    color: '#90391e',
    product: 'vulcan_secadoexpress',
    cat: 'vinilicas',
  },
  {
    codigo: '5042',
    name: 'Gris',
    color: '#47534d',
    product: 'vulcan_secadoexpress',
    cat: 'vinilicas',
  },
  {
    codigo: '5050',
    name: 'Gris',
    color: '#47534d',
    product: 'vulcan_herreros',
    cat: 'vinilicas',
  },
  {
    codigo: '5051',
    name: 'Rojo Óxido',
    color: '#90391e',
    product: 'vulcan_herreros',
    cat: 'vinilicas',
  },
];

export const novedades = [
  {
    id: 1,
    name: '¡Llegaron los nuevos colores metálicos TROPIMAR!',
    description: `Transforma cualquier superficie con el acabado espectacular de nuestros nuevos tonos: Oro, Aluminio y Cobre.
Perfectos para darle un toque sofisticado y artístico a tus proyectos.
Descubre cómo un color puede hacer que todo resalte.

.
`,
    imagen: '/promociones/tropimar.jpg',
    enlace: '/productos',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 2,
    name: '¡Ya está aquí el nuevo VULCAN® PRIMARIO ALTA ADHERENCIA de IPESA Pinturas!',
    description: `Un primario de calidad superior, formulado con resinas acrílicas para ofrecer una adherencia excepcional sobre lámina galvanizada previamente acondicionada.
Ideal para estructuras metálicas como tanques, puertas, maquinaria y más.

`,
    imagen: '/promociones/vulvan_511.jpg',
    enlace: '/productos',
    categoria: 'decorativa',
    microcategoria: 'primarios',
  },
  {
    id: 3,
    name: 'Nueva línea de Pulimentos MENZERNA',
    description: `¡La perfección del pulido automotriz ha llegado a México! Presentamos la nueva línea de pulimentos MENZERNA, ahora disponible con tu distribuidor IPESA Pinturas. Esta tecnología de precisión alemana complementa a la perfección nuestra línea de repintado automotriz Color Cril, ofreciendo una solución completa: desde el color hasta el brillo final.
Con más de 50 años de experiencia, en IPESA Pinturas unimos innovación y calidad para brindarte acabados duraderos y profesionales. Menzerna e IPESA Pinturas, una alianza para lograr pintura impecable y protección superior. ¡Descúbrela hoy!
.
`,
    imagen: '/promociones/menzerna_2025.webp',
    enlace: '/productos',
    categoria: 'automotriz',
    microcategoria: 'pulimentos',
  },
  {
    id: 4,
    name: '"Promoción como caída del cielo"',
    description: `Prepárate para la temporada de lluvias con un 20% de descuento en impermeabilizantes seleccionados, vigente del 1 de marzo al 29 de agosto de 2025. Protege tu hogar con soluciones confiables como IMPER RUF®, IMPER LUX®, IMPER CRIL®, y nuestros impermeabilizantes de muro WALL COVER ECO® y WALL COVER PLUS®, en presentaciones de 18 y 19 litros.
Aprovecha esta oportunidad en tiendas participantes. Consulta productos participantes, restricciones y condiciones con tu distribuidor autorizado IPESA®.
.
`,
    imagen: '/promociones/imperm_2025.webp',
    enlace: '/productos',
    categoria: 'decorativa',
    microcategoria: 'impermeabilizantes',
  },
  //     ,{
  //         id: 5,
  //         name: "Pinta la primavera con IPESA Pinturas",
  //         description: `Dale color a la primavera con un 20% de descuento en nuestras pinturas vinílicas y selladores seleccionados. Del 24 de marzo al 30 de abril de 2025, aprovecha esta promoción exclusiva y renueva tus espacios con productos de alta calidad como VINTEKO, VINIPESA® Mate y Satín, REALTEK®, y selladores SELLATEK® 2 en 1 y SELLATEK® 5x1 en sus presentaciones de 1, 4 y 19 litros.
  // Aplica solo en tiendas participantes y hasta agotar existencias. Consulta productos participantes, términos y condiciones con tu distribuidor autorizado IPESA®.
  // `,
  //         imagen: "/promociones/primavera_2025.webp",
  //         enlace: "/productos",
  //         categoria: "decorativa",
  //         microcategoria: "vinilicas"

  //     }
  // ,{
  //     id: 1,
  //     name: "Nuestra Visión es de colores",
  //     description: `Promoción válida del 10 de septiembre al 19 de octubre de 2024 o hasta agotar existencias. Aplica solo en tiendas participantes. Consulta productos, términos y condiciones. No aplica con otras promociones. Aplican restricciones. Productos participantes VINITEK®, REALTEK®, VINIPESA® MATE Y SATÍN, VINI+, SELLALTEK® 5X1	Y 2 en 1. Cualquier duda acerca de la promoción, consulta con tu distribuidor autorizado IPESA®`,
  //     imagen: "/promociones/1a1.png",
  //     enlace: "/productos",
  //     categoria: "decorativa",
  //     microcategoria: "impermeabilizantes"
  // },{
  //     id: 2,
  //     name: "Promocion caída del cielo, 20% de descuento en impermeabilizantes",
  //     description: `Promoción válida hasta el 30 de septiembre del 2024 o hasta agotar existencias.
  //     Aplica solo en tiendas participantes.
  //     Consulta productos, términos y condiciones,
  //     No aplica con otras promociones. Aplica restricciones. Productos participantes:
  //     Imper Ruf® 3 años. Imper Lux® 5 años, Imper Lux Fibratado 5 años, Imper Cril® 7 años, impermeabilizantes de muro, Wall Cover Eco® 3 años y Wall Cover Plus® 5 años en presentaciones 18 y 19L.
  //     Cualquier duda acerca de la promoción consulta con tu distribuidor autorizado IPESA.`,
  //     imagen: "/promociones/caida_cielo/promo.jpg",
  //     enlace: "/productos",
  //     categoria: "decorativa",
  //     microcategoria: "impermeabilizantes"
  // },
  // {
  //     id: 3,
  //     name: "20% de descuento ",
  //     description: "Promoción válida hasta el 28 de abril del 2024 o hasta agotar existencias. Aplica solo en tiendas participantes. Consulta productos, términos y condiciones, No aplica con otras promociones. Aplica restricciones. Productos participantes: Pintura vinil acrilica VINIPESA® acabo mate o satín y esmalte Tropimar®, en presentaciones  1, 4 y 19 L. Cualquier duda acerca de la promoción consulta con tu distribuidor autorizado IPESA.",
  //     imagen: "/consumidores/promocion.webp",
  //     enlace: "/productos",
  //     categoria: "decorativa",
  //     microcategoria: "vinilicas"
  // },
  // {
  //     id: 4,
  //     name: "Nuestro Rellenador Premium Hyper Light",
  //     description: "Es un rellenador premium, al ser más ligero es mucho más fácil de lijar, reduce por mucho la porosidad y tiene excelente adherencia.",
  //     imagen: "/principal/nuevo_producto.webp",
  //     enlace: "/productos",
  //     categoria: "automotriz",
  //     microcategoria: "rellenadores"
  // },
];

export const consumidores = [
  {
    name: 'Particulares',
    imagen: '/consumidores/particulares.webp',
    description:
      'Transforma tu hogar en un oasis de color y estilo con nuestra pintura IPESA® de la más alta calidad. Nuestros productos están diseñados para brindarte durabilidad, facilidad de aplicación y una amplia gama de colores para que puedas expresar tu creatividad en cada espacio de tu hogar.',
    clase: 'card-animate',
  },
  {
    name: 'Oficios',
    imagen: '/consumidores/oficio.webp',
    description:
      'Potencializa tu trabajo con nuestros portafolios de pintura. Nuestra línea de productos ofrece una excelente cobertura, resistencia y facilidad de aplicación, permitiéndote lograr resultados impecables en cada uno de tus proyectos.',
    clase: 'card-animate2',
  },
  {
    name: 'Profesional',
    imagen: '/consumidores/profesional.webp',
    description:
      'Eleva la calidad de tus proyectos con nuestro portafolio de recubrimientos, diseñados para satisfacer la demanda de los proyectos más exigentes, nuestras pinturas ofrecen: durabilidad, resistencia y una amplia variedad de colores para que puedas ofrecer a tus clientes resultados excepcionales en cada trabajo.',
    clase: 'card-animate3',
  },
];

export const nosotros = [
  {
    id: 1,
    title: 'Misión',
    description:
      'Aplicamos nuestra experiencia en pinturas y recubrimientos para transformar y dar vida a tus espacios, creando entornos inspiradores y funcionales de forma segura y eficiente.',

    clase: 'card-animate',
    imagen: '/principal/n2.webp',
  },
  {
    id: 2,
    title: 'Visión',
    description:
      'Nos comprometemos a preservar lo que más te importa, dando color y protección a tus espacios a través de soluciones innovadoras que cuiden y realcen tus objetos y espacios más valiosos.',

    clase: 'card-animate2',
    imagen: '/principal/n0.webp',
  },
  {
    id: 3,
    title: 'Valores',
    description: '',
    lista: [
      'Ayudar',
      'Excelencia',
      'Calidad',
      'Innovación',
      'Compromiso',
      'Orientación al Cliente',
      'Colaboración',
      'Honestidad',
      'Integridad',
      'Responsabilidad Social',
    ],
    clase: 'card-animate3',
    imagen: '/principal/n1.jpg',
  },
];

export const tipsparapintar = [
  {
    name: 'IPESA, PRUEBA SUPERADA',
    target: 'superada',
  },
  {
    name: 'Línea de accesorios BROTIMEX',
    target: 'brotimex',
  },
  {
    name: 'Sistema de aplicación Vinílicas',
    target: 'vinilicas',
  },
  {
    name: 'Sistema de aplicación Esmaltes',
    target: 'esmaltes',
  },
  // {
  //     name: "Problemas y Soluciones Repintado Automotriz",
  //     target: "automotriz",
  // },
  {
    name: 'Capacitaciones Técnicas',
    target: 'capacitaciones',
  },

  {
    name: 'Tutoriales',
    target: 'tutoriales',
  },
];

export const contenidoTips = [
  {
    id: 'vinilicas',
    title: 'Preparado',
    color: '#2e75b5',
    imagen: '/principal/preparado.jpg',
    description:
      'Toda superficie deberá estar limpia y seca al momento de realizar la aplicación, deberá estar libre de polvo, grasa y humedad.',
  },
  {
    id: 'vinilicas',
    title: 'Sellado',

    color: '#ffc000',
    imagen: '/principal/sellado.jpg',
    description: `Si es obra nueva o una pintura en malas condiciones, se recomienda aplicar un sellador "Vinílico" para promover la adherencia, gastando menos pintura y mejora el acabado.`,
  },
  {
    id: 'vinilicas',
    title: 'Acabado',
    color: '#c55a11',
    imagen: '/principal/acabado.jpg',
    description:
      'Se recomienda aplicar 2 manos de pintura Vinílica con el color de su preferencia, dejando secar entre mano y mano.',
  },

  {
    id: 'esmaltes',
    title: 'Preparado',
    color: '#2e75b5',
    imagen: '/principal/preparado.jpg',
    description:
      'La superficie debe de estar limpia, libre de óxido y contaminantes. Lija previamente.',
  },
  {
    id: 'esmaltes',
    title: 'Sellado',
    color: '#ffc000',
    imagen: '/principal/sellado_esmaltes.jpg',
    description: `Aplica primario Vulcan, diluido del 15 al 30% con tíner, aplica una mano con brocha, pistola o airless.`,
  },
  {
    id: 'esmaltes',
    title: 'Acabado',
    color: '#c55a11',
    imagen: '/principal/acabado.jpg',
    description:
      'Se recomienda aplicar 2 manos de esmalte con brocha, pistola o airless, dejando secar entre mano y mano.',
  },

  {
    id: 'tutoriales',
    name: 'Vintek',
    video: 'https://www.youtube.com/watch?v=uVic436FqTA',
    enlace: '/producto/vintek',
    categoria: 'decorativa',
    microcategoria: 'vinilicas',
  },

  {
    id: 'tutoriales',
    name: 'Vinipesa',
    video: 'https://www.youtube.com/watch?v=60U-4T2KQIM',
    enlace: '/producto/vinipesa-satin',
    categoria: 'decorativa',
    microcategoria: 'vinilicas',
  },
  {
    id: 'tutoriales',
    name: 'Vini +',
    video: 'https://www.youtube.com/watch?v=6QYXimJi5CI',
    enlace: '/producto/vinimas',
    categoria: 'decorativa',
    microcategoria: 'vinilicas',
  },
  {
    id: 'tutoriales',
    name: 'Tropimar Sur',
    video: 'https://www.youtube.com/watch?v=UzDi2_ZJXwo',
    enlace: '/producto/tropimar-sur',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'tutoriales',
    name: 'Tropimar',
    video: 'https://www.youtube.com/watch?v=ujiKUFdQd4s',
    enlace: '/producto/tropimar',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'superada',
    name: 'Restauración con VULCAN y TROPIMAR metálicos',
    video: 'https://www.youtube.com/watch?v=d_iVRaVRDfA',
    enlace: '/producto/tropimar',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'superada',
    name: 'Pulimos un auto con productos MENZERNA y el resultado es brutal',
    video: 'https://www.youtube.com/watch?v=cRtafg659gg&t=53s',
    enlace: '/producto/cut-force-pro',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'superada',
    name: 'Transformamos esta pared en minutos con REALTEK',
    video: 'https://www.youtube.com/watch?v=WBEe17d_Kxw',
    enlace: '/producto/realtek',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'superada',
    name: 'Pintado Automotriz Paso a Paso con Productos COLOR CRIL de Pinturas IPESA',
    video: 'https://www.youtube.com/watch?v=AQ97OqmCFoo&t=17s',
    enlace: '/producto/body-filler-2203',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },

  {
    id: 'superada',
    name: 'Sistema SELLATEK + REALTEK',
    video: 'https://youtu.be/-iplU_d2gGA?si=iSpGSf8_67l_zE9u',
    enlace: '/producto/realtek',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'superada',
    name: 'CENTURY MADERAS: Sistema de Nitrocelulosa',
    video: 'https://youtu.be/iTgG_OW9yFY?si=_ye1GN40iJyDShPV',
    enlace: '/producto/sellador-directo-de-nitro',
    categoria: 'maderas',
    microcategoria: 'maderas',
  },
  {
    id: 'superada',
    name: 'CENTURY MADERAS: Tinta al Alcohol, Fondo y Barniz de Poliuretano',
    video: 'https://youtu.be/6qcU5nE5g9w?si=B4Vu2XBvh-wsobHl',
    enlace: '/producto/tinta-al-alcohol',
    categoria: 'maderas',
    microcategoria: 'maderas',
  },
  {
    id: 'capacitaciones',
    name: 'TEKLINE: VINTEK',
    video: 'https://youtu.be/dAg02GU72Dc?si=2dc_w2S-18DPzKHV',
    enlace: '/producto/vintek',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'vinilicas',
    name: 'TEKLINE (Sistema de aplicación Vinílicas)',
    video: 'https://youtu.be/70wK2KiX0XE?si=FZ0pjVK7JkuuDAQS',
    enlace: '/producto/vintek',
    categoria: 'decorativa',
    microcategoria: 'esmaltes',
  },
  {
    id: 'tutoriales',
    name: 'CENTURY MADERAS: Sistema de Nitrocelulosa',
    video: 'https://youtu.be/iTgG_OW9yFY?si=_ye1GN40iJyDShPV',
    enlace: '/producto/sellador-directo-de-nitro',
    categoria: 'maderas',
    microcategoria: 'maderas',
  },
  {
    id: 'tutoriales',
    name: 'CENTURY MADERAS: Tinta al Alcohol, Fondo y Barniz de Poliuretano',
    video: 'https://youtu.be/6qcU5nE5g9w?si=B4Vu2XBvh-wsobHl',
    enlace: '/producto/tinta-al-alcohol',
    categoria: 'maderas',
    microcategoria: 'maderas',
  },

  {
    id: 'brotimex',
    name: 'Descubre BROTIMEX',
    video: 'https://youtu.be/2rMqIUkFTjA?si=IU8ywlKUh5PnVBZq',
    enlace: null,
    categoria: 'maderas',
    microcategoria: 'maderas',
  },
  {
    id: 'brotimex',
    name: '¡Brochas BROTIMEX!',
    video: 'https://youtu.be/P2s9mihyX90?si=26sZC3wAT7S5omr3',
    enlace: null,
    categoria: 'maderas',
    microcategoria: 'maderas',
  },
];
export const estados = [
  { id: 1, estado: 'Aguascalientes' },
  { id: 2, estado: 'Baja California' },
  { id: 3, estado: 'Baja California Sur' },
  { id: 4, estado: 'Campeche' },
  { id: 5, estado: 'Chiapas' },
  { id: 6, estado: 'Chihuahua' },
  { id: 7, estado: 'Ciudad de México' },
  { id: 8, estado: 'Coahuila' },
  { id: 9, estado: 'Colima' },
  { id: 10, estado: 'Durango' },
  { id: 11, estado: 'Estado de México' },
  { id: 12, estado: 'Guanajuato' },
  { id: 13, estado: 'Guerrero' },
  { id: 14, estado: 'Hidalgo' },
  { id: 15, estado: 'Jalisco' },
  { id: 16, estado: 'Michoacán' },
  { id: 17, estado: 'Morelos' },
  { id: 18, estado: 'Nayarit' },
  { id: 19, estado: 'Nuevo León' },
  { id: 20, estado: 'Oaxaca' },
  { id: 21, estado: 'Puebla' },
  { id: 22, estado: 'Querétaro' },
  { id: 23, estado: 'Quintana Roo' },
  { id: 24, estado: 'San Luis Potosí' },
  { id: 25, estado: 'Sinaloa' },
  { id: 26, estado: 'Sonora' },
  { id: 27, estado: 'Tabasco' },
  { id: 28, estado: 'Tamaulipas' },
  { id: 29, estado: 'Tlaxcala' },
  { id: 30, estado: 'Veracruz' },
  { id: 31, estado: 'Yucatán' },
  { id: 32, estado: 'Zacatecas' },
];

export const tintometricos = [
  {
    id: 1,
    title: 'Equipo',
    description: ' PC con software pre cargado para igualación de color.',
    imagen: '/tintometrico/maquinaFTA.png',
    clase: 'card-animate',
  },
  {
    id: 2,
    title: 'Dosificador',
    description:
      'Dosificador automático secuencial con ajuste para adaptar el tamaño de cada uno de los envases.',
    imagen: '/tintometrico/maquinaFTB.png',
    clase: 'card-animate2',
  },
  {
    id: 3,
    title: 'Mezclador',
    description:
      'Mezclador giroscópico de alto rendimiento y temporizador mecánico, apto para envases de 1 a 19 L.',
    imagen: '/tintometrico/mezcaldor_FT.png',
    clase: 'card-animate3',
  },
];

export const espacios = [
  {
    id: 1,
    space: 'comedor',
    title: 'Comedor',
    imagen: '/descubrecolor/01.jpg',
  },
  {
    id: 2,
    space: 'dormitorio',
    title: 'Dormitorio',
    imagen: '/descubrecolor/02.jpg',
  },
  {
    id: 3,
    space: 'sala',
    title: 'Sala',
    imagen: '/descubrecolor/03.jpg',
  },
  {
    id: 4,
    space: 'baño',
    title: 'Baño',
    imagen: '/descubrecolor/04.jpg',
  },
];

export const estilos = [
  {
    id: 1,
    style: 'contemporaneo',
    title: 'Contemporáneo',
    imagen: '/principal/sala_principal.webp',
  },
  {
    id: 2,
    style: 'minimalista',
    title: 'Minimalista',
    imagen: '/descubrecolor/06.jpg',
  },
  {
    id: 3,
    style: 'escandinavo',
    title: 'Escandinavo',
    imagen: '/decorador/sala2.jpg',
  },
  {
    id: 4,
    style: 'moderno',
    title: 'Moderno',
    imagen: '/descubrecolor/05.jpg',
  },
];

export const coloresDiscover = [
  {
    id: 1,
    estilo: 'contemporaneo',
    name: 'Blanco Ostión',
    codigo: '#fcf8ef',
    codigo2: '1313',
  },
  {
    id: 2,
    estilo: 'contemporaneo',
    name: 'Champaña',
    codigo: '#f5e6cf',
    codigo2: '701',
  },
  {
    id: 3,
    estilo: 'contemporaneo',
    name: 'Crema',
    codigo: '#f8e2bb',
    codigo2: '704',
  },
  {
    id: 4,
    estilo: 'contemporaneo',
    name: 'Cantera Mexicana',
    codigo: '#e6c49f',
    codigo2: '747',
  },

  {
    id: 5,
    estilo: 'moderno',
    name: 'Aqua',
    codigo: '#8dc0bb',
    codigo2: '749',
  },
  {
    id: 6,
    estilo: 'moderno',
    name: 'Azul Océano',
    codigo: '#3157a0',
    codigo2: '748',
  },
  {
    id: 7,
    estilo: 'moderno',
    name: 'Verde Manzana',
    codigo: '#96D346',
    codigo2: '703',
  },
  {
    id: 8,
    estilo: 'moderno',
    name: 'Azul Vallarta',
    codigo: '#73b5e5',
    codigo2: '714',
  },

  {
    id: 9,
    estilo: 'escandinavo',
    name: 'Salmón',
    codigo: '#eec4ac',
    codigo2: '745',
  },
  {
    id: 10,
    estilo: 'escandinavo',
    name: 'Capuchino',
    codigo: '#94856e',
    codigo2: '745',
  },
  {
    id: 11,
    estilo: 'escandinavo',
    name: 'Verde Imperial',
    codigo: '#98a989',
    codigo2: '740',
  },
  {
    id: 12,
    estilo: 'escandinavo',
    name: 'Arena Real',
    codigo: '#f6e0c9',
    codigo2: '430',
  },

  {
    id: 13,
    estilo: 'minimalista',
    name: 'Blanco Mate',
    codigo: '#ffffff',
    codigo2: '770',
  },
  {
    id: 14,
    estilo: 'minimalista',
    name: 'Gris Oxford',
    codigo: '#929292',
    codigo2: '742',
  },
  {
    id: 15,
    estilo: 'minimalista',
    name: 'Gris Bahía',
    codigo: '#dcddd8',
    codigo2: '433',
  },
  {
    id: 16,
    estilo: 'minimalista',
    name: 'Arena',
    codigo: '#f2cf95',
    codigo2: '1303',
  },
];

export const decorador = [
  {
    id: 1,
    registro: '®',
    name: 'vintek',
    categoria: 'vintek',
    fondo: 'rgba(0, 0, 0)',
    imagen: '/articulos/vinilicas/vintek.png',
    filter: 'decorativa',
  },
  {
    id: 2,
    registro: '®',
    name: 'realtek',
    categoria: 'realtek',
    fondo: 'rgba(0, 0, 0, 0.3)',
    imagen: '/articulos/vinilicas/realtek.png',
    filter: 'decorativa',
  },
  {
    id: 3,
    registro: '®',
    name: 'vinipesa',
    name2: 'satín',
    categoria: 'vinipesa_satin',
    fondo: 'rgba(0, 0, 0)',
    imagen: '/articulos/vinilicas/vinipesa_satin.png',
    filter: 'decorativa',
  },
  {
    id: 4,
    registro: '®',
    name: 'vinipesa',
    name2: 'mate',
    categoria: 'vinipesa_mate',
    fondo: 'rgba(0, 0, 0)',
    imagen: '/articulos/vinilicas/vinipesa.png',
    filter: 'decorativa',
  },

  {
    id: 5,
    registro: '®',
    categoria: 'vini_plus',
    name: 'Vini +',
    fondo: 'rgba(0, 0, 0, 0.3)',
    imagen: '/articulos/vinilicas/vini_plus.png',
    filter: 'decorativa',
  },
  {
    id: 6,
    registro: '®',
    name: 'colorbel',
    categoria: 'colorbel',
    fondo: 'rgba(0, 0, 0)',
    imagen: '/articulos/vinilicas/colorbel.png',
    filter: 'decorativa',
  },
  {
    id: 7,
    registro: '®',
    name: 'elite',
    categoria: 'elite',
    fondo: 'rgba(0, 0, 0)',
    imagen: '/articulos/ferreadvance/elite.png',
    filter: 'ferre',
  },
  {
    id: 8,
    registro: '®',
    name: 'imperial',
    categoria: 'imperial',
    fondo: 'rgba(0, 0, 0)',
    imagen: '/articulos/ferreadvance/imperial.png',
    filter: 'ferre',
  },
];
